### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by Shalankwa** [yihuang/credis#12]
Started receiving a new error when trying to import the module. 
version 2.0.1

Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import credis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shalankwa/.local/lib/python3.10/site-packages/credis/__init__.py", line 1, in <module>
    from .base import Connection, RedisProtocolError, RedisReplyError, ConnectionError, AuthenticationError
ModuleNotFoundError: No module named 'credis.base'

version 2.0.0 works fine.

**Comment by yihuang** [comment]
thanks for the notice, it's something with the latest poetry, I just published `v2.0.2`, should fixed the issue.

**Comment by Shalankwa** [comment]
Ty, it's loading again, so I assume all good lol. I'll get back again if we have any other issues 👋
