### ISSUE TITLE
master fails when importing Connection

### ISSUE THREAD

**Issue by RayVR** [yihuang/credis#5]
## In [1]: from credis import Connection

ImportError                               Traceback (most recent call last)
<ipython-input-1-a5645918dbf9> in <module>()
----> 1 from credis import Connection

/Users/rroberts/anaconda/lib/python2.7/site-packages/credis/**init**.py in <module>()
----> 1 from .base import Connection, RedisProtocolError, RedisReplyError, ConnectionError, AuthenticationError

ImportError: cannot import name RedisProtocolError

**Comment by yihuang** [comment]
Strange, i can't reproduct it, please provide information about your environment (python version, os, platform, e.g.).
